name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2-beta
      with: 
        node-version: 12

    - name: Install Yarn
      uses: Borales/actions-yarn@v2.3.0
      with: 
        cmd: install
        
    - name: Build App
      run: yarn build
    
    - name: Install Surge
      run: npm install --global surge 
   
    - name: Surge Deployement
      run: surge ./build http://mybasicapp1.surge.sh/ --token ${{ secrets.SECRET_1 }} 
